#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "-----"
echo "🐺 [Husky]: Executing the pre-commit Git hook..."

pnpm exec lint-staged --verbose

echo ""
echo "🐺 [Husky]: Finished pre-commit hook with success!"
echo ""
